In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("diabetes.csv")
df

pregnancies  glucose  bloodpressure  skinthickness  insulin   bmi  \
0               6    148.0           72.0           35.0      0.0  33.6   
1               1     85.0           66.0           29.0      0.0  26.6   
2               8    183.0           64.0            0.0      0.0  23.3   
3               1     89.0           66.0           23.0     94.0  28.1   
4               0    137.0           40.0           35.0    168.0  43.1   
...           ...      ...            ...            ...      ...   ...   
1531           10    101.0           76.0           48.0    180.0  32.9   
1532            2    122.0           70.0           27.0      0.0  36.8   
1533            5    121.0           72.0           23.0    112.0  26.2   
1534            1    126.0           60.0            0.0      0.0  30.1   
1535            1     93.0           70.0           31.0      0.0  30.4   

      diabetespedigreefunction   age  outcome  
0                        0.627  50.0        1  
1                        0.351  31.0        0  
2                        0.672  32.0        1  
3                        0.167  21.0        0  
4                        2.288  33.0        1  
...                        ...   ...      ...  
1531                     0.171  63.0        0  
1532                     0.340  27.0        0  
1533                     0.245  30.0        0  
1534                     0.349  47.0        1  
1535                     0.315  23.0        0  

[1536 rows x 9 columns]

In [7]:
df.outcome.value_counts()

0    1000
1     536
Name: outcome, dtype: int64

In [8]:
df.describe()

pregnancies      glucose  bloodpressure  skinthickness      insulin  \
count  1536.000000  1532.000000    1530.000000    1528.000000  1530.000000   
mean      3.845052   120.763708      69.101961      20.498691    79.274510   
std       3.368480    31.894098      19.381680      15.930062   114.895763   
min       0.000000     0.000000       0.000000       0.000000     0.000000   
25%       1.000000    99.000000      62.000000       0.000000     0.000000   
50%       3.000000   117.000000      72.000000      23.000000    25.000000   
75%       6.000000   140.000000      80.000000      32.000000   126.000000   
max      17.000000   199.000000     122.000000      99.000000   846.000000   

               bmi  diabetespedigreefunction          age      outcome  
count  1532.000000               1526.000000  1534.000000  1536.000000  
mean     31.994778                  0.471843    33.230769     0.348958  
std       7.870785                  0.331776    11.760723     0.476796  
min       0.000000                  0.078000    21.000000     0.000000  
25%      27.300000                  0.243250    24.000000     0.000000  
50%      32.000000                  0.371000    29.000000     0.000000  
75%      36.600000                  0.626750    41.000000     1.000000  
max      67.100000                  2.420000    81.000000     1.000000

In [11]:
df.isna().sum()

pregnancies                  0
glucose                      4
bloodpressure                6
skinthickness                8
insulin                      6
bmi                          4
diabetespedigreefunction    10
age                          2
outcome                      0
dtype: int64

In [12]:
df.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age', 'outcome'],
      dtype='object')

In [16]:
for col in ['glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age']:
    df[col].replace(0, np.NaN, inplace=True)
    mean_ = df[col].mean()
    df[col].fillna(mean_, inplace=True)

In [17]:
df.isna().sum()

pregnancies                 0
glucose                     0
bloodpressure               0
skinthickness               0
insulin                     0
bmi                         0
diabetespedigreefunction    0
age                         0
outcome                     0
dtype: int64

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [23]:
X = df.iloc[ : , :-1 ]
y = df.outcome

# split data into train and test parts
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [26]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1228, 8), (308, 8), (1228,), (308,))

In [30]:
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7662337662337663

In [31]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [32]:
confusion_matrix(y_test, y_pred)

array([[178,  35],
       [ 37,  58]])

In [33]:
pd.DataFrame( confusion_matrix(y_test, y_pred) )

0   1
0  178  35
1   37  58

In [35]:
X_test.iloc[[0]]

pregnancies  glucose  bloodpressure  skinthickness  insulin   bmi  \
1408            0    102.0           86.0           17.0    105.0  29.3   

      diabetespedigreefunction   age  
1408                     0.695  27.0

In [36]:
y_test.iloc[0]

0

In [37]:
model.predict(X_test.iloc[[0]])

array([0])

In [38]:
model.predict_proba(X_test.iloc[[0]])

array([[0.89949604, 0.10050396]])

In [39]:
# balancing the classes
df1= df.query(" outcome==0 ").sample(n=500, random_state=0)
df2= df.query(" outcome==1 ").sample(n=500, random_state=0)
df3= pd.concat([df1,df2]).sample(n=1000, random_state=0)

In [41]:
df3.shape

(1000, 9)

In [42]:
df.outcome.value_counts()

0    1000
1     536
Name: outcome, dtype: int64

In [43]:
X = df3.iloc[ : , :-1 ]
y = df3.outcome

# split data into train and test parts
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.74

In [44]:
y_pred = model.predict(X_test)

pd.DataFrame( confusion_matrix(y_test, y_pred))

0   1
0  70  22
1  30  78